name: JumpKing
version: '${version}'
main: org.osj.jumpking.JumpKing
api-version: '1.20'

commands:
  uinfo:
    description: display player data
  purchaseLand:
    description: purchase chunk
    aliases: 땅구매
  removeLand:
    description: remove chunk
    aliases: 땅제거
  shopTest:
    description: shopTest
    aliases: 상점테스트
  invite:
    description: invite user
    aliases: 초대
  test:
  changename:
    description: change name
    aliases: 닉네임변경
  changenameop:
    description: change name op
    aliases: 닉네임변경op
  issuegoldbundle:
    description: issue gold bundle
    aliases: 출금